EasShip/EasShip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Customer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('Customer.urls')),
    path('partner_company/', include('PatnerCompany.urls')),
    path('chat/', include('chat.urls')),
    path('refer/', include('Refer.urls')),
    path('', index, name='home'),
    path('login/', include('User.urls')),
    path('api/v1/', include('driver.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EasShip/PatnerCompany/urls.py
from django.urls import include, path, reverse_lazy
from .views import SignUpView, ActivateAccount, partner_company_Home, ProfileView, save_later, SavedJobs, AppliedJobs, \
    remove_applied, remove_saved, ProfileEdit, SignUpVieww, addTransport, addDriver, ManageDriver, ManageTruck, \
    Update_PresentShip, SetUp_PresentShip, PresentShip, DriverRecords, RemoveDriver, RemoveTruck, apply_Shipment, \
    TruckRecords,PastShipment,cancel_setup,Complete_PresentShip
from . import views
from django.contrib.auth import views as auth_views  # import this

app_name = 'partner_company'
urlpatterns = [
    path('', partner_company_Home, name='partner_company_home'),
    path('savedJobs/', SavedJobs, name='SavedJobs'),
    path('appliedJobs/', AppliedJobs, name='AppliedJobs'),
    path('PastShipment/', PastShipment, name='PastShipment'),
    path('removeApplied/<int:pk>', remove_applied, name='remove'),
    path('removeSaved/<int:pk>', remove_saved, name='remove_saved'),
    path('save/<int:pk>', save_later, name='save_job'),
    path('bid/<int:pk>', apply_Shipment, name='apply_Shipment'),
    path('login', views.login_candidate, name='partner_company/login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup', SignUpView.as_view(), name='partner_company/register'),
    path('signup/ref=<uid>', SignUpVieww.as_view(), name='ref'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset.html', email_template_name='account/password_reset_email.html',
        success_url=reverse_lazy('partner_company:password_reset_done')),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url=reverse_lazy('partner_company:password_reset_complete')), name='password_reset_confirm'),
    path('account/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('viewprofile/', ProfileView, name='profile'),
    path('profile_edit/', ProfileEdit, name='ProfileEdit'),
    path('create_profile/', ProfileEdit, name='create_profile'),
    path('addTransport/', addTransport, name='add_transport'),
    path('addDriver/', addDriver, name='add_driver'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('ManageDriver/', ManageDriver, name='ManageDriver'),
    path('ManageTruck/', ManageTruck, name='ManageTruck'),
    path('Update_PresentShip/<int:pk>', Update_PresentShip, name='Update_PresentShip'),
    path('Complete_PresentShip/<int:pk>', Complete_PresentShip, name='Complete_PresentShip'),
    path('SetUp_PresentShip/<int:pk>', SetUp_PresentShip, name='SetUp_PresentShip'),
    path('cancel_SetUp/<int:pk>', cancel_setup, name='cancel_setup'),
    path('PresentShip/', PresentShip, name='PresentShip'),
    path('DriverRecords/', DriverRecords, name='DriverRecords'),
    path('VehicleRecords/', TruckRecords, name='VehicleRecords'),
    path('RemoveDriver/<int:pk>', RemoveDriver, name='RemoveDriver'),
    path('RemoveTruck/<int:pk>', RemoveTruck, name='RemoveTruck'),
]

EasShip/User/urls.py
from django.urls import path
from .views import loginUser

app_name = 'user'
urlpatterns = [
    path('', loginUser, name='Login')
]

EasShip/templates/partner_company/TransprtManagement.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>EasShipp.in</title><link rel = "icon" href ="{% static 'images/green.png' %} "type = "image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.35">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style12.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
 		<style>
.dropbtn {
  background-color: #FFFFFF;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #03A84E;}


		</style>
  </head>
  <body>

	<header>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-12">
					<div class="top-navbar">
						<nav class="navbar navbar-expand-lg ">
  <a class="" href="{% url 'partner_company:partner_company_home' %}"><img src="{% static 'images/green.png' %} " width="60" height="60"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">




	<ul class="navbar-nav ml-auto">



	  <li class="nav-item">
          <a class="nav-link" href="{% url 'partner_company:ManageDriver' %}"><b>Manage Driver</b></a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'partner_company:ManageTruck' %}"><b>Manage Transportation</b></a>
      </li>
        <li class="nav-item">
            <li class="nav-item">
            <a class="nav-link" href="/refer"><b>Refer&Earn</b></a>
      </li>
            <div class="dropdown"><button class="dropbtn nav-link" style="color:black;"><b>Shipments</b></button>
            <div class="dropdown-content">
                <a class="nav-link" href="{% url 'partner_company:SavedJobs' %}">Saved</a>
                <a class="nav-link" href="{% url 'partner_company:AppliedJobs' %}">Applied</a>
                <a class="nav-link" href="{% url 'partner_company:PresentShip' %}">On Going Shipment</a>
                <a class="nav-link" href="{% url 'partner_company:PastShipment' %}">Past Shipment</a>
            </div>
            </div></li>
         <li class="nav-item">
<div class="dropdown">
  <button class="dropbtn">{% if cp.company_logo %}<img src="{{cp.company_logo.url}}">{% else %}<img src="{% static 'images/profile/avatar.png' %}">{% endif %}</button>
  <div class="dropdown-content">
    <a href="{% url 'partner_company:profile' %}">My Profile</a>

    <a href="{% url 'partner_company:logout' %}">Log Out</a>
  </div>
</div>
         </li>


	 </ul>

  </div>
</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

<section class="job-portal">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="heading">
					<h3>Vehicle <span>Management </span></h3>
				</div>
			</div>
            <div class="col-md-10 col-12 mx-auto">
				<div class="heading-action">
					<ul class="list-inline">
						<li>Action <span>Taken</span></li>
                        <li><a href="{% url 'partner_company:VehicleRecords' %}" style="color:#03A84E;">Vehicle Work History</a></li>
						<li><a href="{% url 'partner_company:add_transport' %}" style="color:#03A84E;">Add New Vehicle</a>  </li>

					</ul>
				</div>
			</div>

<div class="col-md-10 col-12 mx-auto">

       {% for o in info %}
				<div class="job-right">
					<div class="job-right-jobs">


            <div class="jobs-main">
            <div class="text-jobs">
      <h5>{{o.0.transport_no_plate}}</h5>
<p><b>{{o.0.type_of_transport}}</b></p>
            </div>
            </div>
    <p class="job-para">

       {% if o.1 %}
        <b>Shipment Status:Assigned</b><br>
        {% for a in o.1 %}
        <div class="row">
          <div class="col">
       <b>Driver</b>:{{a.driver}}<br>
        <b>Driver Phone</b>:{{a.driver.phone}}<br>
        <b>Pickup</b>: {{a.job_id.picking_Address}}<br>
      </div>
      <div class="col">
        <b>Destination</b>:  {{a.job_id.droping_Address}}<br>


        <b>shipment Description</b>:<br>
        {{a.job_id.job_description}}</div></div>{% endfor %}
        {% else %}<b>Shipment Status:Not Assigned</b>{% endif %}
       </p>
  <div class="share">
     <a type="button" href="{% url 'partner_company:RemoveTruck' o.0.pk %}" class="btn btn-danger">Remove Vehicle</a>
  </div>

                    </div>




</div>



{% endfor %}
</div>

        </div>

    </div>

    </section>
    <footer class="bg-dark " style="margin-top: 10px;">
                <div class="container" style="    max-inline-size: inherit;padding-top: 20px;">
                    <div class="row">
                        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="/static/images/" style=" " alt="" width="50" class="mb-3">
                            <p class="font-italic" style="color: white;">Get Shipper for your Shipments !!<br> Tell us what Shipment you want to complete</p>
                            <ul class="list-inline mt-4">
                                <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i style="font-size: xx-large;    color: #00ddf3;" class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i style="font-size: xx-large;color: #007eff;" class="fa fa-facebook"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i style="font-size: xx-large;color: #f704d9;" class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i style="font-size: xx-large;color: #f70404;" class="fa fa-pinterest"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i style="font-size: xx-large;color: #1e04f7;" class="fa fa-vimeo"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Account</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="{% url 'user:Login' %}" class="text" style="color: white;">Login</a></li>
                                <li class="mb-2"><a href="{% url 'partner_company:partner_company/register' %}" class="text" style="color: white;">Shipper Register</a></li>
                                <li class="mb-2"><a href="{% url 'customer:customer/register' %}" class="text" style="color: white;">Customer Register</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Company</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="#" class="text" style="color: white;">About Us</a></li>
                                <li class="mb-2"><a href="#" class="text" style="color: white;">Contact Us</a></li>
                                <!-- <li class="mb-2"><a href="#" class="text-muted">Wishlist</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li> -->
                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-lg-0">

                            <img src="{% static 'images/green.png' %} " width="75" height="75">
                        </div>
                    </div>
                    <!-- Copyrights -->

                </div>


            </footer>
 <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>
</html>

EasShip/templates/partner_company/applied.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>EasShipp.in</title><link rel = "icon" href ="{% static 'images/green.png' %} "type = "image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.35">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style12.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
 		<style>
.dropbtn {
  background-color: #FFFFFF;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #03A84E;}


		</style>
  </head>
  <body>
	<header>
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-12">
					<div class="top-navbar">
						<nav class="navbar navbar-expand-lg ">
  <a class="" href="{% url 'partner_company:partner_company_home' %}"><img src="{% static 'images/green.png' %} " width="60" height="60"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">




	<ul class="navbar-nav ml-auto">



	  <li class="nav-item">
          <a class="nav-link" href="{% url 'partner_company:ManageDriver' %}"><b>Manage Driver</b></a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'partner_company:ManageTruck' %}"><b>Manage Transportation</b></a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/refer"><b>Refer&Earn</b></a>
      </li>
        <li class="nav-item">
            <div class="dropdown"><button class="dropbtn nav-link" style="color:black;"><b>Shipments</b></button>
            <div class="dropdown-content">
                <a class="nav-link" href="{% url 'partner_company:SavedJobs' %}">Saved</a>
                <a class="nav-link" href="{% url 'partner_company:AppliedJobs' %}">Applied</a>
                <a class="nav-link" href="{% url 'partner_company:PresentShip' %}">On Going Shipment</a>
                <a class="nav-link" href="{% url 'partner_company:PastShipment' %}">Past Shipment</a>
            </div>
            </div></li>
         <li class="nav-item">
<div class="dropdown">
  <button class="dropbtn">{% if cp.company_logo %}<img src="{{cp.company_logo.url}}">{% else %}<img src="{% static 'images/profile/avatar.png' %}">{% endif %}</button>
  <div class="dropdown-content">
    <a href="{% url 'partner_company:profile' %}">My Profile</a>

    <a href="{% url 'partner_company:logout' %}">Log Out</a>
  </div>
</div>
         </li>


	 </ul>

  </div>
</nav>
					</div>
				</div>
			</div>
		</div>

	</header>

<section class="job-portal">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="heading">
					<h3>Applied <span>Shipments</span></h3>
					<h4>Shipments you applied in</h4>
				</div>
			</div>

<div class="col-md-10 col-12 mx-auto">

       {% for o in jobs %}
				<div class="job-right">
					<div class="job-right-jobs">
						<div class="job-right-jobs-image">
                                                        <img src={{o.1.company_logo.url}}>

            <div class="jobs-main">
            <div class="text-jobs">
      <h5>{{o.0.job_id.ship_title}}</h5>
                   <p style="font-size:21px">{{o.1.company_name}}</p>
            </div>
            </div>
                        </div>
    <p class="job-para">
        Pickup: {{o.0.job_id.picking_Address}}<br>
        Destination:  {{o.0.job_id.droping_Address}}<br>


        Shipment description:<br>
        {{o.0.job_id.job_description}}
       </p>
  <div class="share">
     <p>
         {% if o.0.is_selected %}
         <a type="button" href="{% url 'partner_company:SetUp_PresentShip' o.0.job_id.pk %}" class="btn btn-success">Set Transportation</a>
         <a type="button" href="{% url 'partner_company:cancel_setup' o.0.job_id.pk %}" class="btn btn-danger">Cancel</a>
         {% elif o.0.is_shortlisted %}
         Status :Is Shortlisted
         {% elif o.0.is_disqualified %}
         Status :Is Disqualified
         {% else %}
         Status :Applied successfully
         {% endif %}
     </p>
  </div>
                    </div>




</div>



{% endfor %}
</div>

        </div>

    </div>

    </section>
<footer class="bg-dark " style="margin-top: 10px;">
                <div class="container" style="    max-inline-size: inherit;padding-top: 20px;">
                    <div class="row">
                        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="/static/images/" style=" " alt="" width="50" class="mb-3">
                            <p class="font-italic" style="color: white;">Get Shipper for your Shipments !!<br> Tell us what Shipment you want to complete</p>
                            <ul class="list-inline mt-4">
                                <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i style="font-size: xx-large;    color: #00ddf3;" class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i style="font-size: xx-large;color: #007eff;" class="fa fa-facebook"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i style="font-size: xx-large;color: #f704d9;" class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i style="font-size: xx-large;color: #f70404;" class="fa fa-pinterest"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i style="font-size: xx-large;color: #1e04f7;" class="fa fa-vimeo"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Account</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="{% url 'user:Login' %}" class="text" style="color: white;">Login</a></li>
                                <li class="mb-2"><a href="{% url 'partner_company:partner_company/register' %}" class="text" style="color: white;">Shipper Register</a></li>
                                <li class="mb-2"><a href="{% url 'customer:customer/register' %}" class="text" style="color: white;">Customer Register</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Company</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="#" class="text" style="color: white;">About Us</a></li>
                                <li class="mb-2"><a href="#" class="text" style="color: white;">Contact Us</a></li>
                                <!-- <li class="mb-2"><a href="#" class="text-muted">Wishlist</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li> -->
                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-lg-0">

                            <img src="{% static 'images/green.png' %} " width="75" height="75">
                        </div>
                    </div>
                    <!-- Copyrights -->

                </div>


            </footer>
 <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>
</html>

EasShip/templates/partner_company/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css'%}">
	<link rel="stylesheet" type="text/css" href=" {% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form p-l-55 p-r-55 p-t-178" method="POST" action="">
					{% csrf_token %}
					<span class="login100-form-title">
						Job Seeker Sign In
					</span>
					{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter username">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Please enter password">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="text-right p-t-13 p-b-23">
						<span class="txt1">
							<a href="{% url 'partner_company:reset_password' %}">Forgot Password</a>
						</span>


					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign in
						</button>
					</div>


				</form>


			</div>
		</div>
	</div>
	
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>