EasShip/Customer/urls.py
from django.urls import include, path, reverse_lazy
from .views import SignUpView, ActivateAccount, login_candidate, customer_home, Add_Shipment, Add_prod_desc, unpublish, \
    remove_unpublish, job_detail, view_applied_candidate, shortlistview_applied_candidate, \
    disqualifyview_applied_candidate, shortlist, delete_job, disqualify, publish_job, ProfileView, job_Response, \
    SignUpVieww, Commission_View, Request_commision, select, Ship_ongoing,ProfileEdit,Bid_detail,handlerequest,payPayment,EditShipment,RequestUpdate,RatingForm,Ejob_detail
from django.contrib.auth import views as auth_views  # import this

app_name = 'customer'
urlpatterns = [
    path('login', login_candidate, name='customer/login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup', SignUpView.as_view(), name='customer/register'),
    path('signup/ref=<uid>', SignUpVieww.as_view(), name='ref'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset.html', email_template_name='account/password_reset_emailre.html',
        success_url=reverse_lazy('customer:password_reset_done')),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url=reverse_lazy('customer:password_reset_complete')), name='password_reset_confirm'),
    path('account/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('', customer_home, name='customer_home'),
    path('add_ship', Add_Shipment, name='job_post'),
    path('add_prod_desc/<int:pk>', Add_prod_desc, name='Add_prod_desc'),
    path('deletejob/<int:pk>', delete_job, name='delete_job'),
    path('jobdetail/<int:pk>', job_detail, name='job_detail'),
    path('Expiredjobdetail/<int:pk>', Ejob_detail, name='Ejob_detail'),
    path('Biddetail/<int:pk>', Bid_detail, name='Bid_detail'),
    path('RateShipment/<int:pk>', RatingForm, name='rate'),
    path('requestUpdate/<int:pk>', RequestUpdate, name='RequestUpdate'),
    path('jobdetail/publishjob/<int:pk>', publish_job, name='publish_job'),
    path('EditShipment/<int:pk>', EditShipment, name='edit_ship'),
    path('jobdetail/applied_candidate/<int:pk>', view_applied_candidate, name='view_applied_candidate'),
    path('jobdetail/applied_candidate/shortlistview/<int:pk>', shortlistview_applied_candidate,
         name='shortlist_view_applied_candidate'),
    path('jobdetail/applied_candidate/disqualifyview/<int:pk>', disqualifyview_applied_candidate,
         name='disqualify_view_applied_candidate'),
    path('jobdetail/applied_candidate/shortlist/<int:pk>', shortlist, name='shortlist'),
    path('jobdetail/applied_candidate/disqualify/<int:pk>', disqualify, name='disqualify'),
    path('jobdetail/applied_candidate/select/<int:pk>', select, name='select'),
    path('unpublish/<int:pk>', unpublish, name='unpublish'),
    path('removeunpublish/<int:pk>', remove_unpublish, name='remove_unpublish'),
    path('viewprofile/', ProfileView, name='profile'),
    path('profile_edit/', ProfileEdit, name='ProfileEdit'),
    path('create_profile/', ProfileEdit, name='create_profile'),
    path('account/', Commission_View, name='Commission'),
    path('account/request', Request_commision, name='Request_commision'),
    path('shipOnProgress/', Ship_ongoing, name='ShipOngoing'),
    path("checkout/<int:pk>", payPayment, name="Checkout"),
    path("handlerequest/",handlerequest, name="HandleRequest"),
]

EasShip/EasShip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Customer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('Customer.urls')),
    path('partner_company/', include('PatnerCompany.urls')),
    path('chat/', include('chat.urls')),
    path('refer/', include('Refer.urls')),
    path('', index, name='home'),
    path('login/', include('User.urls')),
    path('api/v1/', include('driver.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EasShip/PatnerCompany/urls.py
from django.urls import include, path, reverse_lazy
from .views import SignUpView, ActivateAccount, partner_company_Home, ProfileView, save_later, SavedJobs, AppliedJobs, \
    remove_applied, remove_saved, ProfileEdit, SignUpVieww, addTransport, addDriver, ManageDriver, ManageTruck, \
    Update_PresentShip, SetUp_PresentShip, PresentShip, DriverRecords, RemoveDriver, RemoveTruck, apply_Shipment, \
    TruckRecords,PastShipment,cancel_setup,Complete_PresentShip
from . import views
from django.contrib.auth import views as auth_views  # import this

app_name = 'partner_company'
urlpatterns = [
    path('', partner_company_Home, name='partner_company_home'),
    path('savedJobs/', SavedJobs, name='SavedJobs'),
    path('appliedJobs/', AppliedJobs, name='AppliedJobs'),
    path('PastShipment/', PastShipment, name='PastShipment'),
    path('removeApplied/<int:pk>', remove_applied, name='remove'),
    path('removeSaved/<int:pk>', remove_saved, name='remove_saved'),
    path('save/<int:pk>', save_later, name='save_job'),
    path('bid/<int:pk>', apply_Shipment, name='apply_Shipment'),
    path('login', views.login_candidate, name='partner_company/login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup', SignUpView.as_view(), name='partner_company/register'),
    path('signup/ref=<uid>', SignUpVieww.as_view(), name='ref'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset.html', email_template_name='account/password_reset_email.html',
        success_url=reverse_lazy('partner_company:password_reset_done')),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url=reverse_lazy('partner_company:password_reset_complete')), name='password_reset_confirm'),
    path('account/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('viewprofile/', ProfileView, name='profile'),
    path('profile_edit/', ProfileEdit, name='ProfileEdit'),
    path('create_profile/', ProfileEdit, name='create_profile'),
    path('addTransport/', addTransport, name='add_transport'),
    path('addDriver/', addDriver, name='add_driver'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('ManageDriver/', ManageDriver, name='ManageDriver'),
    path('ManageTruck/', ManageTruck, name='ManageTruck'),
    path('Update_PresentShip/<int:pk>', Update_PresentShip, name='Update_PresentShip'),
    path('Complete_PresentShip/<int:pk>', Complete_PresentShip, name='Complete_PresentShip'),
    path('SetUp_PresentShip/<int:pk>', SetUp_PresentShip, name='SetUp_PresentShip'),
    path('cancel_SetUp/<int:pk>', cancel_setup, name='cancel_setup'),
    path('PresentShip/', PresentShip, name='PresentShip'),
    path('DriverRecords/', DriverRecords, name='DriverRecords'),
    path('VehicleRecords/', TruckRecords, name='VehicleRecords'),
    path('RemoveDriver/<int:pk>', RemoveDriver, name='RemoveDriver'),
    path('RemoveTruck/<int:pk>', RemoveTruck, name='RemoveTruck'),
]

EasShip/User/urls.py
from django.urls import path
from .views import loginUser

app_name = 'user'
urlpatterns = [
    path('', loginUser, name='Login')
]

EasShip/chat/urls.py
from django.urls import include, path, reverse_lazy
from .views import room,send,getMessages
from django.contrib.auth import views as auth_views  # import this

app_name = 'chat'
urlpatterns = [
    path('<str:room>/',room,name ='room'),
    path('send', send, name='send'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),
]

EasShip/chat/models.py
from django.db import models
from User.models import User_custom
from datetime import datetime
from Customer.models import customer
from PatnerCompany.models import comp_Bids, patnerComp

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=1000)
    userc = models.ForeignKey(customer, on_delete=models.CASCADE,null=True)
    userp = models.ForeignKey(patnerComp,on_delete=models.CASCADE,null=True)
    bid = models.ForeignKey(comp_Bids,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return f"{self.name}-{self.userc}-{self.userp}"


class Message(models.Model):
    value = models.CharField(max_length=1000000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.ForeignKey(User_custom, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    username = models.CharField(max_length=1000,null=True)
    message_read = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.username} send in Room : {self.room}"

EasShip/chat/views.py
from django.shortcuts import render
from .models import Room, Message
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from Customer.models import customer, Customer_profile
from PatnerCompany.models import patnerComp, Comp_profile


# Create your views here.
@login_required(login_url='/')
def room(request, room):
    user = request.user
    username = request.GET.get('username')
    room_details = Room.objects.get(name=room)
    return render(request, 'chat/room.html', {
        'user': user,
        'username': username,
        'room': room,
        'room_details': room_details
    })


@login_required(login_url='/')
def send(request):
    message = request.POST['message']
    user = request.user
    name = user.first_name + " " + user.last_name
    room_id = request.POST['room_id']
    room = Room.objects.get(pk=room_id)

    new_message = Message.objects.create(value=message, user=user, username=name, room=room)
    new_message.save()
    return HttpResponse('Message sent successfully')


@login_required(login_url='/')
def getMessages(request, room):
    muser = []
    image = []
    room_details = Room.objects.get(name=room)
    useronline = request.user
    messages = Message.objects.filter(room=room_details.id)
    for m in messages:
        muser.append(m.user.user_name)
        if m.user.is_customer:
            c = customer.objects.get(user=m.user)
            cp = Customer_profile.objects.get(cust=c)
            image.append(cp.company_logo.url)
        elif m.user.is_company:
            p = patnerComp.objects.get(user=m.user)
            pp = Comp_profile.objects.get(comp=p)
            image.append(pp.company_logo.url)

    return JsonResponse(
        {"messages": list(messages.values()), "image": image, "muser": muser, "Ruser": useronline.user_name})

EasShip/templates/chat/room.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>EasShipp.in</title><link rel = "icon" href ="{% static 'images/green.png' %} "type = "image/x-icon">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.35">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="bootstrap.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style12.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
          <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  		<style>
.dropbtn {
  background-color: #FFFFFF;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #03A84E;}
		.job-left.job-left-images-new img {
    width: 270px;
    height: 270px;
    border-radius: 50%;
}
.job-left-desc {
    background: rgba(255, 255, 255, 1);
    box-shadow: 0 0px 50px 0px rgb(0 0 1 / 25%);
}

.job-left.job-left-images-new {
    position: relative;
}

.job-left.job-left-images-new:after {content: "";position: absolute;background: #fff;top: 22%;left: 0;width: 100%;height: 30%;z-index: -1;
    background: rgba(255, 255, 255, 1);
    box-shadow: 0 0px 50px 0px rgb(0 0 1 / 25%);
}
.job-left.job-left-images-new {
    background: transparent;
    box-shadow: none;
}
.job-left-desc {
    background: rgba(255, 255, 255, 1);
    box-shadow: 0 39px 50px 0px rgb(0 0 1 / 14%);
}

.xyz {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}
.green {
  border-color: #ccc;
  background-color: #008000;
  color:white;
}


.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>
{% if user.is_company %}
<header>

					<div class="top-navbar">
						<nav class="navbar navbar-expand-lg ">
  <a class="" href="{% url 'partner_company:partner_company_home' %}"><img src="{% static 'images/green.png' %} " width="60" height="60"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">




	<ul class="navbar-nav ml-auto">



	  <li class="nav-item">
          <a class="nav-link" href="{% url 'partner_company:ManageDriver' %}"><b>Manage Driver</b></a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'partner_company:ManageTruck' %}"><b>Manage Transportation</b></a>
      </li>
        <li class="nav-item">
            <div class="dropdown"><button class="dropbtn nav-link" style="color:black;"><b>Shipments</b></button>
            <div class="dropdown-content">
                <a class="nav-link" href="{% url 'partner_company:SavedJobs' %}">Saved</a>
                <a class="nav-link" href="{% url 'partner_company:AppliedJobs' %}">Applied</a>
                <a class="nav-link" href="{% url 'partner_company:PresentShip' %}">On Going Shipment</a>
                <a class="nav-link" href="{% url 'partner_company:PastShipment' %}">Past Shipment</a>
            </div>
            </div></li>
         <li class="nav-item">
<div class="dropdown">
  <button class="dropbtn">{% if cp.company_logo %}<img src="{{cp.company_logo.url}}">{% else %}<img src="{% static 'images/profile/avatar.png' %}">{% endif %}</button>
  <div class="dropdown-content">
    <a href="{% url 'partner_company:profile' %}">My Profile</a>

    <a href="{% url 'partner_company:logout' %}">Log Out</a>
  </div>
</div>
         </li>


	 </ul>

  </div>
</nav>
					</div>


	</header>
{% else %}
<header>

                    <div class="top-navbar">
                        <nav class="navbar navbar-expand-lg ">
                            <a class="" href="{% url 'customer:customer_home' %}"> <img src="{% static 'images/green.png' %} " width="60" height="60"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">



                                <ul class="navbar-nav ml-auto">

                                    <li class="nav-item ">
                                        <a class="nav-link" href="{% url 'customer:job_post' %}"><b>Add New Shipment</b></a>

                                    </li>
                                    <!--	  <li class="nav-item">-->
                                    <!--        <a class="nav-link" href="#">Resume</a>-->
                                    <!--      </li>-->


                                    <li class="nav-item">
                                        <div class="dropdown">
                                            <button class="dropbtn"><img src={{ep.company_logo.url}}></button>
                                            <div class="dropdown-content">
                                                <a href="{% url 'customer:profile' %}">My Profile</a>
                                                <a href="{% url 'customer:logout' %}">Log Out</a>
                                            </div>
                                        </div>
                                    </li>

                                </ul>

                            </div>
                        </nav>
                    </div>


    </header>
{% endif %}


<div class="xyz">
    <div class="heading">
					<h2>Shipment Title: <span>{{room}}</span></h2>

				</div>

<div id="display">
{{messenger}}
<!-- <div class="container darker">
  <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
  <span class="time-left">20th, April 2021</span>
</div> -->

</div>

<script>
$(document).ready(function(){

setInterval(function(){
    $.ajax({
        type: 'GET',
        url : "/chat/getMessages/{{room}}/",

        success: function(response){
            console.log(response);
            $("#display").empty();
            for (var key in response.messages)
            {
                    if(response.muser[key]==response.Ruser){
                    var temp="<div class='container green'><p>"+response.messages[key].value+"</p><span class='time-right'>"+"</span></div>";
                    $("#display").append(temp);
}
                    else{
                    var temp="<div class='container'><p>"+response.messages[key].value+"</p><span class='time-left'>"+"</span></div>";
                    $("#display").append(temp);
                    }
            }
        },
        error: function(response){
            alert('An error occured')
        }
    });
},1000);
})
</script>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

    <form id="post-form">
        {% csrf_token %}
        <input type="hidden" name="username" id="username" value="{{username}}"/>
        <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}"/>
        <input type="text" name="message" id="message" width="100px" />
        <input type="submit" value="Send">
    </form>
</div>

</div>
</body>

<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/chat/send',
      data:{
          username:$('#username').val(),
          room_id:$('#room_id').val(),
          message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>

</html>