EasShip/Customer/urls.py
from django.urls import include, path, reverse_lazy
from .views import SignUpView, ActivateAccount, login_candidate, customer_home, Add_Shipment, Add_prod_desc, unpublish, \
    remove_unpublish, job_detail, view_applied_candidate, shortlistview_applied_candidate, \
    disqualifyview_applied_candidate, shortlist, delete_job, disqualify, publish_job, ProfileView, job_Response, \
    SignUpVieww, Commission_View, Request_commision, select, Ship_ongoing,ProfileEdit,Bid_detail,handlerequest,payPayment,EditShipment,RequestUpdate,RatingForm,Ejob_detail
from django.contrib.auth import views as auth_views  # import this

app_name = 'customer'
urlpatterns = [
    path('login', login_candidate, name='customer/login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup', SignUpView.as_view(), name='customer/register'),
    path('signup/ref=<uid>', SignUpVieww.as_view(), name='ref'),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset.html', email_template_name='account/password_reset_emailre.html',
        success_url=reverse_lazy('customer:password_reset_done')),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html",
        success_url=reverse_lazy('customer:password_reset_complete')), name='password_reset_confirm'),
    path('account/reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('', customer_home, name='customer_home'),
    path('add_ship', Add_Shipment, name='job_post'),
    path('add_prod_desc/<int:pk>', Add_prod_desc, name='Add_prod_desc'),
    path('deletejob/<int:pk>', delete_job, name='delete_job'),
    path('jobdetail/<int:pk>', job_detail, name='job_detail'),
    path('Expiredjobdetail/<int:pk>', Ejob_detail, name='Ejob_detail'),
    path('Biddetail/<int:pk>', Bid_detail, name='Bid_detail'),
    path('RateShipment/<int:pk>', RatingForm, name='rate'),
    path('requestUpdate/<int:pk>', RequestUpdate, name='RequestUpdate'),
    path('jobdetail/publishjob/<int:pk>', publish_job, name='publish_job'),
    path('EditShipment/<int:pk>', EditShipment, name='edit_ship'),
    path('jobdetail/applied_candidate/<int:pk>', view_applied_candidate, name='view_applied_candidate'),
    path('jobdetail/applied_candidate/shortlistview/<int:pk>', shortlistview_applied_candidate,
         name='shortlist_view_applied_candidate'),
    path('jobdetail/applied_candidate/disqualifyview/<int:pk>', disqualifyview_applied_candidate,
         name='disqualify_view_applied_candidate'),
    path('jobdetail/applied_candidate/shortlist/<int:pk>', shortlist, name='shortlist'),
    path('jobdetail/applied_candidate/disqualify/<int:pk>', disqualify, name='disqualify'),
    path('jobdetail/applied_candidate/select/<int:pk>', select, name='select'),
    path('unpublish/<int:pk>', unpublish, name='unpublish'),
    path('removeunpublish/<int:pk>', remove_unpublish, name='remove_unpublish'),
    path('viewprofile/', ProfileView, name='profile'),
    path('profile_edit/', ProfileEdit, name='ProfileEdit'),
    path('create_profile/', ProfileEdit, name='create_profile'),
    path('account/', Commission_View, name='Commission'),
    path('account/request', Request_commision, name='Request_commision'),
    path('shipOnProgress/', Ship_ongoing, name='ShipOngoing'),
    path("checkout/<int:pk>", payPayment, name="Checkout"),
    path("handlerequest/",handlerequest, name="HandleRequest"),
]

EasShip/EasShip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Customer.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('Customer.urls')),
    path('partner_company/', include('PatnerCompany.urls')),
    path('chat/', include('chat.urls')),
    path('refer/', include('Refer.urls')),
    path('', index, name='home'),
    path('login/', include('User.urls')),
    path('api/v1/', include('driver.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EasShip/User/urls.py
from django.urls import path
from .views import loginUser

app_name = 'user'
urlpatterns = [
    path('', loginUser, name='Login')
]

EasShip/chat/urls.py
from django.urls import include, path, reverse_lazy
from .views import room,send,getMessages
from django.contrib.auth import views as auth_views  # import this

app_name = 'chat'
urlpatterns = [
    path('<str:room>/',room,name ='room'),
    path('send', send, name='send'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),
]

EasShip/Customer/views.py
from datetime import datetime
import json
import requests
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from .utils import generate_id
import paytmchecksum
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.views.generic import View
from User.models import User_custom, Referral, Commission_request
from .forms import SignUpForm, ShipJob, Prod_Detail, Profile
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_text, force_bytes
from .tokens import account_activation_token
from .models import customer, Customer_profile, ProdDesc, shipJob, Expired_ShipJob, \
    Shipment_Related_Question
from PatnerCompany.models import shipJob_jobanswer, comp_Bids, Comp_address, Comp_profile, comp_Transport, \
    comp_PresentWork, comp_PastWork, comp_drivers, Orders
from django.contrib.auth.decorators import login_required
from chat.models import Room
payment_id = "XiCkyY61890791146830"
payment_key = "PzkUpfSbO1sD5Be3"


# Create your views here.

class SignUpView(View):
    form_class = SignUpForm

    template_name = 'customer/signup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        print(User_custom.objects.all())
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            emaill = form.cleaned_data['email']
            if User_custom.objects.filter(email=emaill).exists():

                return HttpResponse('User with same email already exists, Please try again with different Username!!')
            else:
                user = form.save(commit=False)
                user.username = user.email
                user.user_name = user.email
                user.is_active = False  # change this to False after testing
                user.is_customer = True
                user.save()
                new_candidate = customer(user=user, is_email_verified=False)  # change is email to False after testing
                new_candidate.save()
                current_site = get_current_site(request)
                subject = 'Activate Your EasShipp Account'
                message = render_to_string('emails/account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                user.email_user(subject, message)
                messages.success(
                    request, ('Please check your mail for complete registration.'))
                return redirect('user:Login')
                # return render(request, self.template_name, {'form': form})
        else:
            return render(request, self.template_name, {'form': form})


class SignUpVieww(View):
    form_class = SignUpForm

    template_name = 'account/signup.html'

    @classmethod
    def ref(self, request, uid, *args, **kwargs):
        form = self.form_class()
        # link = request.GET.get('ref=', None)
        return render(request, self.template_name, {'form': form, 'uid': uid})

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        print(User_custom.objects.all())
        return render(request, self.template_name, {'form': form})

    def post(self, request, uid, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            emaill = form.cleaned_data['email']
            if User_custom.objects.filter(email=emaill).exists():

                return HttpResponse('User with same email already exists, Please try again with different Username!!')
            else:
                user = form.save(commit=False)
                user.username = user.email
                user.user_name = user.email
                user.is_active = False  # change this to False after testing
                user.is_customer = True  # Deactivate account till it is confirmed
                user.save()

                reff = Referral(referred_by_id=uid, user_id=user.pk)
                reff.save()
                new_candidate = customer(user=user, is_email_verified=False)  # change is email to False after testing
                new_candidate.save()
                current_site = get_current_site(request)
                subject = 'Activate Your FinTop Account'
                message = render_to_string('emails/account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                user.email_user(subject, message)
                messages.success(
                    request, ('Please check your mail for complete registration.'))
                # return redirect('login')
                return render(request, self.template_name, {'form': form})
        else:
            return render(request, self.template_name, {'form': form})


class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User_custom.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User_custom.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True

            pr = customer.objects.get(user=user)
            pr.is_email_verified = True
            pr.save()
            user.save()
            login(request, user)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('customer:customer_home')
        else:
            messages.warning(
                request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('user:Login')


def index(request):
    return render(request, 'index.html')


def login_candidate(request):
    if request.user.is_authenticated and request.user.is_customer:
        print(request.user)
        return redirect('customer:customer_home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('pass')
            # print(username)
            # print(password)
            user = authenticate(request, username=username, password=password)

            if user is not None and user.is_customer:
                login(request, user)
                return redirect('customer:customer_home')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'customer/login.html', context)

@login_required(login_url='/')
def customer_home(request):
    jobs = []
    expired_job = []
    count = []
    sj = []
    cb = []
    c__p = []
    
    user = request.user
    context = {}

    if user is not None and user.is_customer:

        try:
            e = customer.objects.get(user=user)
        except customer.DoesNotExist:
            e = None
        # uncomment this after making the profile update correct
        # if Employer_profile.objects.get(employer=e):

        try:
            ep = Customer_profile.objects.get(cust=e)
        except Customer_profile.DoesNotExist:
            ep = None
        if user.first_login:
            try:
                j = shipJob.objects.get(cust=e,is_completed=True)
            except shipJob.DoesNotExist:
                j=None
            if j :
                return redirect('customer:rate',j.pk)
            job = shipJob.objects.filter(cust=e).exclude(bid_selected=True)
            print(job)
            for j in job:
                start_date = j.created_on
                # print(start_date)
                today = datetime.now()
                # print(type(today))
                stat_date = str(start_date)
                start_date = stat_date[:19]
                tday = str(today)
                today = tday[:19]
                s_date = datetime.strptime(start_date, "%Y-%m-%d %H:%M:%S")
                e_date = datetime.strptime(today, "%Y-%m-%d %H:%M:%S")
                # print(s_date)
                # print(e_date)
                diff = abs((e_date - s_date).days)
                print(diff)

                if diff > 14:
                    Expired_ShipJob.objects.create(cust=j.cust, ship_title=j.ship_title,
                                                   job_description=j.job_description, picking_Address=j.picking_Address,
                                                   droping_Address=j.droping_Address).save()

                    j.delete()

                else:
                    jobs.append(j)
                    c_b = comp_Bids.objects.filter(job_id=j)
                    
                    if c_b is None:
                        count.append(0)
                    else:
                        count.append(c_b.count())
            expired_job = Expired_ShipJob.objects.filter(cust=e)
            
            sjob = shipJob.objects.filter(cust=e, bid_selected=True)

EasShip/templates/customer/Commission_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{total}}
</body>
</html>

EasShip/templates/customer/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{user}}
{% for j in jobs %}
<div>
{{j.ship_title}}</div>
{% endfor %}
</body>
</html>

EasShip/templates/customer/job_candidate.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>EasShipp.in</title><link rel = "icon" href ="{% static 'images/green.png' %} "type = "image/x-icon">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.35">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style12.css'%}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"/>
       <!-- THIS LINE -->
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<script src="https://kit.fontawesome.com/5a2b925216.js" crossorigin="anonymous"></script>

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>
    .dropbtn {
  background-color: #FFFFFF;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #03A84E;}


</style>
  </head>
  <body>


    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-12">
                    <div class="top-navbar">
                        <nav class="navbar navbar-expand-lg ">
                            <a class="" href="{% url 'customer:customer_home' %}"> <img src="{% static 'images/green.png' %} " width="60" height="60"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">



                                <ul class="navbar-nav ml-auto">

                                    <li class="nav-item ">
                                        <a class="nav-link" href="{% url 'customer:job_post' %}"><b>Add New Shipment</b></a>

                                    </li>
                                    <!--	  <li class="nav-item">-->
                                    <!--        <a class="nav-link" href="#">Resume</a>-->
                                    <!--      </li>-->

<li class="nav-item">
            <a class="nav-link" href="/refer"><b>Refer&Earn</b></a>
      </li>
                                    <li class="nav-item">
                                        <div class="dropdown">
                                            <button class="dropbtn"><img src={{cp.company_logo.url}}></button>
                                            <div class="dropdown-content">
                                                <a href="{% url 'customer:profile' %}">My Profile</a>
                                                <a href="{% url 'customer:logout' %}">Log Out</a>
                                            </div>
                                        </div>
                                    </li>

                                </ul>

                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

    </header>
       <section class="job-portal all-jobs">
	<div class="container main-wid">
		<div class="row">
			<div class="col-md-10 col-12 mx-auto">
				<div class="heading">
					<h3>{{job.job_title}}</h3>
				</div>
			</div>

			<div class="col-md-10 col-12 mx-auto">
				<div class="heading-action">
					<ul class="list-inline">
						<li>Action <span>Taken</span></li>
                        <li><a href="{% url 'customer:shortlist_view_applied_candidate' job.pk %}" style="color: green;">Shortlisted Shippers</a></li>
						<li><a href="{% url 'customer:disqualify_view_applied_candidate' job.pk %}" style="color: green;"> Disqualified Shippers</a>  </li>

					</ul>
				</div>
			</div>





    {% for c in candidate %}


   <div class="col-md-10 col-12 mx-auto">
{% if c.2.is_shortlisted %}
    {% elif c.2.is_disqualified %}
       {% elif c.2.is_selected %}
Already Selected
    {% else %}
				<div class="job-right all-job-rights">
					<div class="job-right-jobs">
          
					<!-- <input type="checkbox" placehlder="check"> -->

<div class="col-md-10 col-12 mx-auto">
						<div class="job-right-jobs-image">

						<img src={{c.0.company_logo.url}}>
						<div class="jobs-main">
            
							<div class="text-jobs">
                                <h5>{{c.0.company_name}}</h5>
                              <h3>{{c.1.first_name}} {{c.1.last_name}}</h3>
                              


                
							</div>
              

              
                            </div>
					</div>
          
               <div class="info">
							<div class="info-left">
								<ul class="list-inline">
                           	<li>Email ID: <span>{{c.1.username}}</span></li>
									<li> Phone no. : <span>{{c.0.phone}}</span></li>
									<li>Bid Placed: <span>{{c.2.Bid_amount}}</span></li>
									<li>Shipment will be done in :  <span>{{c.2.complete_in}}(days)</span></li>
                                    <li>Total shipment done:  <span>{{c.3}} </span></li>
                                    <li>Rating:  <span>{{c.4}} </span></li>

								</ul>
                
							</div>
                  
						</div>
            </div>

            



<div class="download">
                                <a class="btn btn-success" href="{% url 'customer:select' c.2.pk %}" role="button">Select</a>
                                <a class="btn btn-outline-success  " href="{% url 'customer:shortlist' c.2.pk %}" role="button">Shortlist</a>
                                <a class="btn btn-outline-danger" href="{% url 'customer:disqualify' c.2.pk %}" role="button">Reject</a>
                                <a class="btn btn-outline-info" href="{% url 'chat:room' c.5.name %}" role="button">Chat Room</a>


    
</div>





</div>





    {% endif %}
                    </div>


       </div>

                    {% endfor %}





			</div>
	</div>
</section>

<!-- skills model -->


<footer class="bg-dark " style="margin-top: 10px;">
                <div class="container" style="    max-inline-size: inherit;padding-top: 20px;">
                    <div class="row">
                        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0"><img src="/static/images/" style=" " alt="" width="50" class="mb-3">
                            <p class="font-italic" style="color: white;">Get Shipper for your Shipments !!<br> Tell us what Shipment you want to complete</p>
                            <ul class="list-inline mt-4">
                                <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i style="font-size: xx-large;    color: #00ddf3;" class="fa fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i style="font-size: xx-large;color: #007eff;" class="fa fa-facebook"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i style="font-size: xx-large;color: #f704d9;" class="fa fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i style="font-size: xx-large;color: #f70404;" class="fa fa-pinterest"></i></a></li>
                                <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i style="font-size: xx-large;color: #1e04f7;" class="fa fa-vimeo"></i></a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Account</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="{% url 'user:Login' %}" class="text" style="color: white;">Login</a></li>
                                <li class="mb-2"><a href="{% url 'partner_company:partner_company/register' %}" class="text" style="color: white;">Shipper Register</a></li>
                                <li class="mb-2"><a href="{% url 'customer:customer/register' %}" class="text" style="color: white;">Customer Register</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                            <h6 class="text-uppercase font-weight-bold mb-4" style="color:white">Company</h6>
                            <ul class="list-unstyled mb-0">
                                <li class="mb-2"><a href="#" class="text" style="color: white;">About Us</a></li>
                                <li class="mb-2"><a href="#" class="text" style="color: white;">Contact Us</a></li>
                                <!-- <li class="mb-2"><a href="#" class="text-muted">Wishlist</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li> -->
                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-lg-0">

                            <img src="{% static 'images/green.png' %} " width="75" height="75">
                        </div>
                    </div>
                    <!-- Copyrights -->

                </div>


            </footer>

<style>
ul#menu li {
  display:inline;
}
#spacer {
padding: 21px;

}


.menu-text{
  font-size: 0.7em;

}
.download{
  margin-top: 4px;

}
.btm{
position:absolute;
bottom:10px;
}


.bgcolor {
  min-height: 320px;
  float: right;
  background-color: #ced4da;
}

.job-right-jobs{
box-shadow:0px;
padding:5px;
}
*{
box-sizing:unset;
}
.job-right.all-job-rights .job-right-jobs {
    padding: 0px 0px 0px 0px;
}

.card-header{
background-color:#ced4da;
}



</style>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>